### PR TITLE
Add Workspace 'Use current directory button'

### PR DESCRIPTION
**Pull request by madkins23**
This started with the title above, I wanted to be able to just use the `files-viewer` concept of the "current" directory without browsing through the entire directory tree when adding a new workspace.

I started by adding a button to populate the path text field. Then while I was testing it and I kept tweaking things:
* I added code to only enable the `OK` button when
  * there is some non-whitespace in the name text field and
  * the path text field contains the path of an existing directory.
* I rearranged the layout to put the path text field populating buttons closer to it.

So not all that many things but still more than I intended. If I went overboard or you hate the new layout just say so.

### CODE REVIEW

**Comment by Syntacticlosure** [comment]
The layout is really wired:
image
image

**Comment by madkins23** [comment]
Put it all the buttons on one line again?

**Comment by Syntacticlosure** [comment]
> Put it all the buttons on one line again?

Exchange the places of the OK Button and the Cancel Button?

**Comment by madkins23** [comment]
Done

**Comment by Syntacticlosure** [comment]
Sorry, I misoperated.

**Pull request merged**
